// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technicalservicesprogram.DataAccess.Context;

#nullable disable

namespace technicalservicesprogram.DataAccess.Migrations
{
    [DbContext(typeof(TspDatabase))]
    [Migration("20251006122925_InitialUpdate")]
    partial class InitialUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.DateUserCreate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("UserAppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserAppId");

                    b.ToTable("DateUserCreate");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.TimeUserCreate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("CreateTime")
                        .HasColumnType("time");

                    b.Property<string>("UserAppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserAppId");

                    b.ToTable("TimeUserCreate");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.RoleApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9a4f0a34-7636-403c-a76b-dff0641abb20",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6df545a-b4ad-40bb-932d-9ced3ff8f751",
                            Email = "stoy@sakarya.edu.tr",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Serkan",
                            NormalizedEmail = "STOY@SAKARYA.EDU.TR",
                            NormalizedUserName = "STOY",
                            PasswordHash = "XOnj12+jImVcaXKn7pbSspKwYeWSz4+eyQfF/TOMElQ=",
                            PhoneNumber = "0(564) 295 50 92",
                            PhoneNumberConfirmed = false,
                            Salt = "System.Byte[]",
                            SecurityStamp = "649e1589-e876-442b-9e82-d41d5bf160f4",
                            SicilNo = "944",
                            SurName = "TOY",
                            TwoFactorEnabled = false,
                            UserName = "stoy"
                        },
                        new
                        {
                            Id = "089d6e50-2972-43be-9f8f-6d379e146fe3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e03f424a-fbb4-4a95-9ec9-c4a8f76bbb69",
                            Email = "stoy@sakarya.edu.tr",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Serkan",
                            NormalizedEmail = "STOY@SAKARYA.EDU.TR",
                            NormalizedUserName = "STOY",
                            PasswordHash = "miism5gLi6mAAECA4DEdc2Uatfz0eDjpNcJRUcFaenA=",
                            PhoneNumber = "0(564) 295 50 92",
                            PhoneNumberConfirmed = false,
                            Salt = "System.Byte[]",
                            SecurityStamp = "362f4c6b-1634-4bae-86f7-5205836f3c91",
                            SicilNo = "944",
                            SurName = "TOY",
                            TwoFactorEnabled = false,
                            UserName = "stoy"
                        });
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.DateUserCreate", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", "UserApp")
                        .WithMany("DateUserCreates")
                        .HasForeignKey("UserAppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserApp");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.TimeUserCreate", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", "UserApp")
                        .WithMany("TimeUserCreates")
                        .HasForeignKey("UserAppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserApp");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserApp", b =>
                {
                    b.Navigation("DateUserCreates");

                    b.Navigation("TimeUserCreates");
                });
#pragma warning restore 612, 618
        }
    }
}
