// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technicalservicesprogram.DataAccess.Context;

#nullable disable

namespace technicalservicesprogram.DataAccess.Migrations
{
    [DbContext(typeof(TspDatabase))]
    partial class TspDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.DateUserCreate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("UserAppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserAppId");

                    b.ToTable("DateUserCreate");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.TimeUserCreate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("CreateTime")
                        .HasColumnType("time");

                    b.Property<string>("UserAppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserAppId");

                    b.ToTable("TimeUserCreate");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.RoleApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "41c391e9-f548-48c1-9311-930802f48e09",
                            ConcurrencyStamp = "57AA576B-CDFC-419B-8931-B87610968C26",
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = "54b4e991-3813-4545-920d-7050e61b3058",
                            ConcurrencyStamp = "DAD5A942-2152-4B60-ACD8-0D5E60A32963",
                            Name = "NormalUser",
                            NormalizedName = "NORMALUSER"
                        },
                        new
                        {
                            Id = "2e4a750b-d4f4-47d4-95fb-67f7df6d7c93",
                            ConcurrencyStamp = "722F9B03-43AA-4B0A-AD14-5D1777DE506C",
                            Name = "TechnicalUser",
                            NormalizedName = "TECHNICALUSER"
                        },
                        new
                        {
                            Id = "c59b3110-479f-434b-ad9c-ac65242eca0c",
                            ConcurrencyStamp = "21E52A10-B6FE-4748-913F-25872E628423",
                            Name = "ManagerUser",
                            NormalizedName = "MANAGERUSER"
                        },
                        new
                        {
                            Id = "384faf28-09f4-4156-9c10-7b9615e0f92f",
                            ConcurrencyStamp = "7DC15A1B-4A16-4A30-A22E-6F54FD874E46",
                            Name = "PresidentUser",
                            NormalizedName = "PRESIDENTUSER"
                        },
                        new
                        {
                            Id = "28e7483a-559f-4147-9b50-950fccc41ea5",
                            ConcurrencyStamp = "57AA576B-CDFC-419B-8931-B87610968C26",
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = "a82c8941-6b63-4b90-ab65-ac65d3c98c4a",
                            ConcurrencyStamp = "DAD5A942-2152-4B60-ACD8-0D5E60A32963",
                            Name = "NormalUser",
                            NormalizedName = "NORMALUSER"
                        },
                        new
                        {
                            Id = "88efb253-0c49-4852-9143-6a35010d4e5b",
                            ConcurrencyStamp = "722F9B03-43AA-4B0A-AD14-5D1777DE506C",
                            Name = "TechnicalUser",
                            NormalizedName = "TECHNICALUSER"
                        },
                        new
                        {
                            Id = "0450413e-448d-4c98-a23d-08d0d5fef55b",
                            ConcurrencyStamp = "21E52A10-B6FE-4748-913F-25872E628423",
                            Name = "ManagerUser",
                            NormalizedName = "MANAGERUSER"
                        },
                        new
                        {
                            Id = "69d840bd-4988-41c3-af3c-b32249bea165",
                            ConcurrencyStamp = "7DC15A1B-4A16-4A30-A22E-6F54FD874E46",
                            Name = "PresidentUser",
                            NormalizedName = "PRESIDENTUSER"
                        });
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "80ac1eee-599a-4ca7-8bf4-cba798af90e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00077fc7-8d4c-476a-bb7b-280c477ac234",
                            Email = "stoy@sakarya.edu.tr",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Serkan",
                            NormalizedEmail = "STOY@SAKARYA.EDU.TR",
                            NormalizedUserName = "STOY",
                            PasswordHash = "NanUhnJqj+DsAQKggXcVImWW9IcNZeS2G5e+/6ihIMI=",
                            PhoneNumber = "0(564) 295 50 92",
                            PhoneNumberConfirmed = false,
                            Salt = "System.Byte[]",
                            SecurityStamp = "8b45a77a-78a4-4da8-9c10-1dd6b0dab718",
                            SicilNo = "944",
                            SurName = "TOY",
                            TwoFactorEnabled = false,
                            UserName = "stoy"
                        },
                        new
                        {
                            Id = "242c0c94-4526-4804-9bb5-82bf3572df60",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bafb0857-b312-4698-8278-00b22b8ff1a9",
                            Email = "stoy@sakarya.edu.tr",
                            EmailConfirmed = false,
                            IsActive = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Serkan",
                            NormalizedEmail = "STOY@SAKARYA.EDU.TR",
                            NormalizedUserName = "STOY",
                            PasswordHash = "+MqlmcYh1RXUIYjWCo2gR1X1nQqN6/JnBJrwNGK+Gdw=",
                            PhoneNumber = "0(564) 295 50 92",
                            PhoneNumberConfirmed = false,
                            Salt = "System.Byte[]",
                            SecurityStamp = "bf188b3b-bdb0-46f7-9def-c6d4b91afaa4",
                            SicilNo = "944",
                            SurName = "TOY",
                            TwoFactorEnabled = false,
                            UserName = "stoy"
                        });
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.DateUserCreate", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", "UserApp")
                        .WithMany("DateUserCreates")
                        .HasForeignKey("UserAppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserApp");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.CreateUpdateDelete.TimeUserCreate", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", "UserApp")
                        .WithMany("TimeUserCreates")
                        .HasForeignKey("UserAppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserApp");
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.RoleClaim", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.RoleApp", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserClaim", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserLogin", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserRole", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.RoleApp", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserToken", b =>
                {
                    b.HasOne("technicalservicesprogram.Entities.Core.Users.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technicalservicesprogram.Entities.Core.Users.UserApp", b =>
                {
                    b.Navigation("DateUserCreates");

                    b.Navigation("TimeUserCreates");
                });
#pragma warning restore 612, 618
        }
    }
}
